import tkinter as tk
import back_app as td
def adicionar_doc():
    cod_txt= tk.Label(janela,text="Codigo")
    cod_txt.pack()
    caixa_cod= tk.Entry(janela)
    caixa_cod.pack()
    codigo=caixa_cod.get()
    tipo_txt= tk.Label(janela,text="Tipo")
    tipo_txt.pack()
    caixa_tipo= tk.Entry(janela)
    caixa_tipo.pack()
    tipo= caixa_tipo.get()
    nome_txt= tk.Label(janela,text="Nome")
    nome_txt.pack()
    caixa_nome= tk.Entry(janela)
    caixa_nome.pack()
    titular= caixa_nome.get()
    data_txt= tk.Label(janela,text="Data")
    data_txt.pack()
    caixa_data= tk.Entry(janela)
    caixa_data.pack()
    data= caixa_data.get()
    descri_txt= tk.Label(janela, text="Descrição")
    descri_txt.pack()
    caixa_descri= tk.Entry(janela)
    caixa_descri.pack()
    td.adcionar(codigo,tipo,titular,data)
    botao_comfirmar= tk.Button(janela, text="Comfirmar", width=10, height=1)
    botao_comfirmar.pack()
    botao_adicionar.config(state=tk.DISABLED)
    botao_pesquisa.config(state=tk.DISABLED)
    botao_remover.config(state=tk.DISABLED)
    botao_listar.config(state=tk.DISABLED) 
def remover_doc():
    cod_txt= tk.Label(janela,text="Codigo")
    cod_txt.pack()
    caixa_cod= tk.Entry(janela)
    caixa_cod.pack()
    codigo=caixa_cod.get()
    td.remover(codigo)
    botao_adicionar.config(state=tk.DISABLED)
    botao_pesquisa.config(state=tk.DISABLED)
    botao_remover.config(state=tk.DISABLED)
    botao_listar.config(state=tk.DISABLED)
def pesquisar_doc():
    cod_txt= tk.Label(janela,text="Codigo")
    cod_txt.pack()
    caixa_doc=tk.Entry(janela)
    caixa_doc.pack()
    botao_comfirmar= tk.Button(janela, text="Comfirmar", width=10, height=1)
    botao_comfirmar.pack()
    botao_adicionar.config(state=tk.DISABLED)
    botao_pesquisa.config(state=tk.DISABLED)
    botao_remover.config(state=tk.DISABLED)
    botao_listar.config(state=tk.DISABLED)
def listar_doc():
    cod_txt= tk.Label(janela,text="Codigo")
    cod_txt.pack()
    caixa_doc=tk.Entry(janela)
    caixa_doc.pack()
    botao_comfirmar= tk.Button(janela, text="Comfirmar", width=10, height=1)
    botao_comfirmar.pack()
    botao_adicionar.config(state=tk.DISABLED)
    botao_pesquisa.config(state=tk.DISABLED)
    botao_remover.config(state=tk.DISABLED)
    botao_listar.config(state=tk.DISABLED)
janela= tk.Tk()
janela.geometry("800x600")
janela.title("Almoxarifado")
texto1= tk.Label(janela,text="ALMOXARIFADO")
texto1.pack()
botao_adicionar= tk.Button(janela, text="Adicionar", command=adicionar_doc,width=10, height=1)
botao_adicionar.pack()
botao_remover= tk.Button(janela, text="Remover", command=remover_doc,width=10, height=1)
botao_remover.pack()
botao_pesquisa= tk.Button(janela, text="Pesquisar",command=pesquisar_doc,width=10, height=1)
botao_pesquisa.pack()
botao_listar= tk.Button(janela, text="Listar", command=listar_doc,width=10, height=1)
botao_listar.pack()
janela.mainloop()
